project:
  type: website
  output-dir: docs
  execute-dir: project
  render:
    - "*.md"
    - "*.qmd"
    - "*.Rmd"
    - "!R/*"
  post-render:
    - touch docs/.nojekyll

website:
    title: "PNF 2022"
    site-url: "https://precision-nutrition-forum.github.io/2022/"
    repo-url: "https://github.com/precision-nutrition-forum/2022"
    repo-branch: main
    repo-actions: [edit, issue, source]
    search:
        location: navbar
        type: overlay
    navbar:
        left:
            - icon: "house-door"
              href: "index.qmd"
              text: " "
        right:
            - about.qmd
            - program.qmd
            - text: "Presentations"
              menu:
                - talks.qmd
                - posters.qmd
    page-footer:
        center:
            - text: "License: CC BY-NC-SA 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}} {{< fa brands creative-commons-sa >}}"
              href: LICENSE.md

format:
  html:
    theme:
        - litera
        - theme.scss
    toc: true

editor: visual

