project:
  type: website

website:
  title: "PNF 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
    right:
      - about.qmd
      - text: "Program"
        menu:
        - schedule.qmd
        - speakers.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

