---
title: "Program"
execute:
    freeze: auto
---

```{r setup, include=FALSE, results='markup'}
library(tidyverse)
library(lubridate)
library(glue)
library(here)
library(gt)
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r program-prep}
program <- read_csv(here("data/program.csv"), na = "", guess_max = 0, col_types = "c") %>%
    select(speaker_id, date, session, full_name, title) %>%
    mutate(across(everything(), ~ if_else(is.na(.), "", .))) %>%
    mutate(
        talk = if_else(full_name == "", title, as.character(
            glue("[*{title}*](/talks/{speaker_id}/index.md)")
        )), 
        days = str_to_sentence(format(as_date(date), format = "%B %d"))
    ) %>%
    rename_with(str_to_sentence) 

dates <- program %>% 
    pull(Days) %>% 
    unique()

create_table <- function(data) {
    data %>%
        select(Session, Talk, Full_name) %>%
        gt(groupname_col = "Session") %>%
        tab_style(style = list(cell_text(weight = "bold")),
                  locations = cells_row_groups()) %>%
        tab_style(style = list(cell_text(weight = "bold")),
                  locations = cells_column_labels()) %>%
        opt_table_lines("none") %>%
        opt_table_outline("none") %>% 
        opt_row_striping() %>% 
        fmt_markdown(columns = everything()) %>% 
        tab_options(column_labels.hidden = TRUE)
}
```

::: panel-tabset
## `r dates[1]`

```{r}
program %>% 
    filter(Days == dates[1]) %>% 
    create_table()
```

## `r dates[2]`

```{r}
program %>% 
    filter(Days == dates[2]) %>% 
    create_table()
```
:::
